name: Container
on:
  workflow_dispatch:

jobs:

  release-create:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Release
        run: gh release create $(date +"%Y%m%d")
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux-arm-v5:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - run: docker build -t bin . --build-arg PLATFORM=linux/arm/v5

      - run: docker run --rm -e "INPUT_ARGS" -e "HOME" -v "/home/runner/work/bin/bin":"/github/workspace" -it bin
      
      - name: Release
        run: gh release upload $(date +"%Y%m%d") jit_streamer-*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
